dist: xenial

language: python

#branches:
#  only:
#    - master

matrix:
  include:
    - stage: Lint (Python 3.6)
      python: 3.6
      env: TOXENV=isort,black,flake8,pylint

    - stage: Tests (Python 2.7)
      python: 2.7
      env: TOXENV=py27

    - stage: Tests (Python 3.6)
      python: 3.6
      env: TOXENV=py36

    - stage: Tests (Python 3.7)
      python: 3.7
      env: TOXENV=py37

    - stage: Tests (Python 3.8)
      python: 3.8
      env: TOXENV=py38

install:
  - pip install tox

script:
  - tox