name: Run Tests
on: [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. This prevents duplicated runs on internal PRs.
    # Some discussion of this here:
    # https://github.community/t/duplicate-checks-on-push-and-pull-request-simultaneous-event/18012
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Poetry 🔧
        uses: ThePalaceProject/circulation/.github/actions/poetry@main
        with:
          version: "1.3.2"

      - name: Install dependencies
        run: |
          poetry install --only ci
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Run Tests
        run: tox
